/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "sparkplug.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Payload, Payload, AUTO)


PB_BIND(Payload_Template, Payload_Template, AUTO)


PB_BIND(Payload_Template_Parameter, Payload_Template_Parameter, AUTO)


PB_BIND(Payload_Template_Parameter_ParameterValueExtension, Payload_Template_Parameter_ParameterValueExtension, AUTO)


PB_BIND(Payload_DataSet, Payload_DataSet, AUTO)


PB_BIND(Payload_DataSet_DataSetValue, Payload_DataSet_DataSetValue, AUTO)


PB_BIND(Payload_DataSet_DataSetValue_DataSetValueExtension, Payload_DataSet_DataSetValue_DataSetValueExtension, AUTO)


PB_BIND(Payload_DataSet_Row, Payload_DataSet_Row, AUTO)


PB_BIND(Payload_PropertyValue, Payload_PropertyValue, AUTO)


PB_BIND(Payload_PropertyValue_PropertyValueExtension, Payload_PropertyValue_PropertyValueExtension, AUTO)


PB_BIND(Payload_PropertySet, Payload_PropertySet, AUTO)


PB_BIND(Payload_PropertySetList, Payload_PropertySetList, AUTO)


PB_BIND(Payload_MetaData, Payload_MetaData, AUTO)


PB_BIND(Payload_Metric, Payload_Metric, 2)


PB_BIND(Payload_Metric_MetricValueExtension, Payload_Metric_MetricValueExtension, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

